//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtomasyonLokanta
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adisyons
    {
        public int Adisyon_Id { get; set; }
        public int Siparis_Id { get; set; }
        public Nullable<int> Servis_Id { get; set; }
        public Nullable<int> Adet { get; set; }
    
        public virtual Servislers Servislers { get; set; }
        public virtual Siparislers Siparislers { get; set; }
    }
}
