//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtomasyonLokanta
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kategoriler
    {
        public Kategoriler()
        {
            this.Servislers = new HashSet<Servislers>();
        }
    
        public int Kategori_Id { get; set; }
        public string Kategori_Ad { get; set; }
    
        public virtual ICollection<Servislers> Servislers { get; set; }
    }
}
