//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtomasyonLokanta
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LokantaDbEntities : DbContext
    {
        public LokantaDbEntities()
            : base("name=LokantaDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<C__EFMigrationsHistory> C__EFMigrationsHistory { get; set; }
        public DbSet<Adisyons> Adisyons { get; set; }
        public DbSet<Kategoriler> Kategoriler { get; set; }
        public DbSet<Masalars> Masalars { get; set; }
        public DbSet<Personellers> Personellers { get; set; }
        public DbSet<Rollers> Rollers { get; set; }
        public DbSet<Servislers> Servislers { get; set; }
        public DbSet<Siparislers> Siparislers { get; set; }
    }
}
