//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtomasyonLokanta
{
    using System;
    using System.Collections.Generic;
    
    public partial class Masalars
    {
        public Masalars()
        {
            this.Personellers = new HashSet<Personellers>();
            this.Siparislers = new HashSet<Siparislers>();
        }
    
        public int Masa_Id { get; set; }
        public string Masa_Ad { get; set; }
        public bool Masa_Durum { get; set; }
    
        public virtual ICollection<Personellers> Personellers { get; set; }
        public virtual ICollection<Siparislers> Siparislers { get; set; }
    }
}
