//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtomasyonLokanta
{
    using System;
    using System.Collections.Generic;
    
    public partial class Servislers
    {
        public Servislers()
        {
            this.Adisyons = new HashSet<Adisyons>();
        }
    
        public int Servis_Id { get; set; }
        public string Servis_Ad { get; set; }
        public int Kategori_Id { get; set; }
        public Nullable<double> Fiyat { get; set; }
        public string Servis_Image { get; set; }
    
        public virtual ICollection<Adisyons> Adisyons { get; set; }
        public virtual Kategoriler Kategoriler { get; set; }
    }
}
