//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtomasyonLokanta
{
    using System;
    using System.Collections.Generic;
    
    public partial class Siparislers
    {
        public Siparislers()
        {
            this.Adisyons = new HashSet<Adisyons>();
        }
    
        public int Siparis_Id { get; set; }
        public int Masa_Id { get; set; }
        public System.DateTime Acilis { get; set; }
        public System.DateTime Kapanis { get; set; }
    
        public virtual ICollection<Adisyons> Adisyons { get; set; }
        public virtual Masalars Masalars { get; set; }
    }
}
